config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :links
  root to: 'visitors#index'
  get ':controller(/:action)'
  get '/devise/locales/german', to: 'locales#german'
  get '/devise/locales/english', to: 'locales#english'
  get '/high_voltage/locales/german', to: 'locales#german'
  get '/high_voltage/locales/english', to: 'locales#english'
end

app/models/link.rb
class Link < ActiveRecord::Base
  belongs_to :user
  validates :url, presence: true
  validates :url, format: { with: URI.regexp }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :links
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :set_link, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:show, :create, :edit, :update, :destroy]

  # GET /links
  # GET /links.json
  def index
    @links = Link.all
  end

  # GET /links/1
  # GET /links/1.json
  def show
  end

  # GET /links/new
  def new
    @link = Link.new
  end

  # GET /links/1/edit
  def edit
  end

  # POST /links
  # POST /links.json
  def create
    @link = Link.new(link_params)
    @link.user_id = current_user.id

    respond_to do |format|
      if @link.save
        format.html { redirect_to links_url, notice: t('models.link.created') }
        format.json { render :show, status: :created, location: @link }
      else
        format.html { render :new }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /links/1
  # PATCH/PUT /links/1.json
  def update
    respond_to do |format|
      if @link.update(link_params)
        format.html { redirect_to @link, notice: t('models.link.updated') }
        format.json { render :show, status: :ok, location: @link }
      else
        format.html { render :edit }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /links/1
  # DELETE /links/1.json
  def destroy
    @link.destroy
    respond_to do |format|
      format.html { redirect_to links_url, notice: t('models.link.destroyed') }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_link
      @link = Link.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def link_params
      params.require(:link).permit(:name, :url)
    end
end

app/controllers/locales_controller.rb
class LocalesController < ApplicationController

  def english
    I18n.locale = :en
    redirect_to :back
  end

  def german
    I18n.locale = :de
    redirect_to :back
  end
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
  def index
    @links = Link.order(:created_at).take(5)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/links_helper.rb
module LinksHelper
  def confirm_link_deletion(link)
    "#{t('messages.delete.link', name: link.name)}"
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="container">
    <p class="text-muted">
      <%= link_to image_tag('blank.png', class: 'flag flag-gb'), { :controller => 'locales', :action => 'english' } %>
      <%= link_to image_tag('blank.png', class: 'flag flag-de'), { :controller => 'locales', :action => 'german' } %>
    </p>
  </div>
</footer>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to t('nav.home'), root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
      <p class="navbar-text pull-right">
        <% if user_signed_in? %>
          <%= t('devise.logged_in') %> <strong><%= current_user.email %></strong>.
          <%= link_to t('devise.edit_profile'), edit_user_registration_path, :class => 'navbar-link' %> |
          <%= link_to t('devise.logout'), destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
        <% else %>
          <%= link_to t('devise.sign_up'), new_user_registration_path, :class => 'navbar-link'  %> |
          <%= link_to t('devise.login'), new_user_session_path, :class => 'navbar-link'  %>
        <% end %>
      </p>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li><%= link_to t('nav.about'), page_path('about') %></li>
<li><%= link_to t('nav.links'), links_path %></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Licol" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Licol" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
      <%= render 'layouts/messages' %>
      <div class='jumbotron'>
        <%= yield %>
      </div>
    </main>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/links/_form.html.erb
<%= simple_form_for(@link) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :url %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/links/_index_for_anonymous.html.erb
<table class='table table-striped'>
  <thead>
    <tr>
      <th><%= t('activerecord.attributes.link.name') %></th>
      <th><%= t('activerecord.attributes.link.url') %></th>
    </tr>
  </thead>

  <tbody>
    <% @links.each do |link| %>
      <tr>
        <td><%= link.name %></td>
        <td><%= link_to link.url, link.url %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/links/_index_for_user.html.erb
<table class='table table-striped'>
  <thead>
    <tr>
      <th><%= t('activerecord.attributes.link.name') %></th>
      <th><%= t('activerecord.attributes.link.url') %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @links.each do |link| %>
      <tr>
        <td><%= link.name %></td>
        <td><%= link_to link.url, link.url %></td>
        <td><%= link_to content_tag(:span, '', :class => 'glyphicon glyphicon-search'), link %></td>
        <td><%= link_to content_tag(:span, '', :class => 'glyphicon glyphicon-pencil'), edit_link_path(link) %></td>
        <td><%= link_to content_tag(:span, '', :class => 'glyphicon glyphicon-remove'), link, method: :delete, data: { confirm: confirm_link_deletion(link) } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to t('models.link.new'), new_link_path %>

app/views/links/_list.html.erb
<ul class='list-group'>
  <% @links.each do |link| %>
    <li class='list-group-item'>
      <%= link_to link.name, link.url %>
    </li>
  <% end %>
</ul>

app/views/links/edit.html.erb
<h1><%= t('models.link.edit') %></h1>

<%= render 'form' %>

<%= link_to t('crud.show'), @link %> |
<%= link_to t('nav.back'), links_path %>

app/views/links/index.html.erb
<h1><%= t('models.link.list') %></h1>

<% if user_signed_in? %>
  <%= render 'index_for_user' %>
<% else %>
  <%= render 'index_for_anonymous' %>
<% end %>

app/views/links/new.html.erb
<h1><%= t('models.link.new') %></h1>

<%= render 'form' %>

<%= link_to t('nav.back'), links_path %>

app/views/links/show.html.erb
<p>
  <strong><%= t('models.link.name') %>:</strong>
  <%= @link.name %>
</p>

<p>
  <strong><%= t('models.link.url') %>:</strong>
  <%= link_to link.url, link.url %>
</p>

<%= link_to t('crud.edit'), edit_link_path(@link) %> |
<%= link_to t('nav.back'), links_path %>

app/views/pages/about.html.erb
<% content_for :title do t('nav.about') end %>
<h3><%= t('nav.about') %></h3>
<p><%= simple_format t('app.about') %></p>

app/views/visitors/index.html.erb
<h3><%= t('app.welcome') %></h3>

<% unless @links.blank? %>
  <h4><%= t('app.link_list') %></h4>
  <%= render 'links/list' %>
<% end %>